---
version: "3.7"

services:
  openldap:
    build: ./images/ldap
    ports:
      - "389:389"
    #command: tail -f /dev/null
    command: /usr/bin/start-ldap.sh
    networks:
      - internal

  mariadb:
    build: ./images/mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=ldaptest
      - MARIADB_DATABASE=ldaptest
      - MARIADB_USER=ldaptest
      - MARIADB_PASSWORD=ldaptest
    networks:
      - internal

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    ports:
      - "8080:80"
    networks:
      - internal
      - web
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false

networks:
  internal:
  web:
    external: true
